use crate::span::Span;

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span) -> Self {
        Self { kind, span }
    }
}

impl Keyword {
    pub fn lexeme(self) -> &'static str {
        match self {
            Keyword::Import => "import",
            Keyword::As => "as",
            Keyword::Extern => "extern",
            Keyword::Fun => "fun",
            Keyword::Async => "async",
            Keyword::Let => "let",
            Keyword::Var => "var",
            Keyword::Const => "const",
            Keyword::Struct => "struct",
            Keyword::Enum => "enum",
            Keyword::Trait => "trait",
            Keyword::Impl => "impl",
            Keyword::Return => "return",
            Keyword::In => "in",
            Keyword::If => "if",
            Keyword::Else => "else",
            Keyword::While => "while",
            Keyword::For => "for",
            Keyword::Switch => "switch",
            Keyword::Try => "try",
            Keyword::Catch => "catch",
            Keyword::Unsafe => "unsafe",
            Keyword::Assembly => "assembly",
            Keyword::Slice => "slice",
            Keyword::Tuple => "tuple",
            Keyword::Mut => "mut",
            Keyword::Await => "await",
            Keyword::True => "true",
            Keyword::False => "false",
            Keyword::Break => "break",
            Keyword::Continue => "continue",
            Keyword::Use => "use",
            Keyword::Mod => "mod",
            Keyword::Type => "type",
            Keyword::Pub => "pub",
            Keyword::Check => "check",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Keyword {
    Import,
    As,
    Extern,
    Fun,
    Async,
    Let,
    Var,
    Const,
    Struct,
    Enum,
    Trait,
    Impl,
    Return,
    In,
    If,
    Else,
    While,
    For,
    Switch,
    Try,
    Catch,
    Unsafe,
    Assembly,
    Slice,
    Tuple,
    Mut,
    Await,
    True,
    False,
    Break,
    Continue,
    Use,
    Mod,
    Type,
    Pub,
    Check,
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Identifier(String),
    IntegerLiteral(String),
    FloatLiteral(String),
    StringLiteral(String),
    CharLiteral(char),
    Keyword(Keyword),
    LeftBrace,
    RightBrace,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    Comma,
    Dot,
    DotDot,
    Semicolon,
    Colon,
    ColonColon,
    ThinArrow,
    Equals,
    EqualEqual,
    BangEqual,
    Ampersand,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Question,
    Bang,
    Pipe,
    AmpersandAmpersand,
    PipePipe,
    At,
    Eof,
}
